version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "1080:80"
    # volumes:
    #   - ./code:/code # will be delted later
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./code:/code # will be delted later
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
volumes:
  db_data:
