version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - php
#       - db
#   php:
#     image: php:fpm
#     volumes:
#       - ./code:/code
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: rootpassword
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
