version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "1080:80"
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
